### ISSUE TITLE
AnalysisParameters Threshold choices

### ISSUE THREAD

**Issue by kkiwimagi** [TASBE/TASBEFlowAnalytics-Tutorial#10]
How are minimum bin counts and contamination thresholds chosen?

AP=setMinValidCount(AP,100');% Ignore any bins with less than valid count as noise
AP=setPemDropThreshold(AP,5');% Ignore any raw fluorescence values less than this threshold as too contaminated by instrument noise

**Comment by jakebeal** [comment]
Both of these thresholds are about ignoring highly quantized and thus often misleading information.

The min valid count is about the fact that with very small numbers of cells, the numbers you see are very heavily influenced by individual cells.  Thus, the uncertainty in the statistics becomes quite large.

The drop threshold is because flow values are typically quantized to integers, so we lose resolution badly in the 1-10 range, where the difference between 1 and 2 is a whole 1/3 of a decade.

They are both set to reasonable defaults, but can be moved up or down if desired.  To disable them, set them to zero.
